SUBTTL	SWITCHES,MACROS.

REALIO=4			;5=STM
				;4=APPLE.
				;3=COMMODORE.
				;2=OSI
				;1=MOS TECH,KIM
				;0=PDP-10 SIMULATING 6502
INTPRC==1			;INTEGER ARRAYS.
ADDPRC==1			;FOR ADDITIONAL PRECISION.
LNGERR==0			;LONG ERROR MESSAGES.
TIME==	0			;CAPABILITY TO SET AND READ A CLK.
EXTIO== 0			;EXTERNAL I/O.
DISKO== 0			;SAVE AND LOAD COMMANDS
NULCMD==1			;FOR THE "NULL" COMMAND
GETCMD==1
RORSW==1
ROMSW==1			;TELLS IF THIS IS ON ROM.
CLMWID==14
LONGI==1			;LONG INITIALIZATION SWITCH.
STKEND=511
BUFPAG==0
LINLEN==72			;TERMINAL LINE LENGTH.
BUFLEN==72			;INPUT BUFFER SIZE.
ROMLOC= ^O20000			;ADDRESS OF START OF PURE SEGMENT.
KIMROM=1
IFE	ROMSW,<KIMROM==0>
IFN	REALIO-1,<KIMROM==0>
IFN	ROMSW,<
RAMLOC= ^O40000			;USED ONLY IF ROMSW=1
IFE	REALIO,<ROMLOC= ^O20000 ;START AT 8K.
	RAMLOC=^O1400>>
IFE	REALIO-3,<
	DISKO==1
	RAMLOC==^O2000
	ROMLOC=^O140000
	NULCMD==0
	GETCMD==1
	linlen==40
	BUFLEN==81
	CQOPEN=^O177700
	CQCLOS=^O177703
	CQOIN= ^O177706		;OPEN CHANNEL FOR INPUT
	CQOOUT=^O177711		;FILL FOR COMMO.
	CQCCHN=^O177714
	CQINCH=^O177717		;INCHR'S CALL TO GET A CHARACTER
	OUTCH= ^O177722
	CQLOAD=^O177725
	CQSAVE=^O177730
	CQVERF=^O177733
	CQSYS= ^O177736
	ISCNTC=^O177741
	CZGETL=^O177744		;CALL POINT FOR "GET"
	CQCALL=^O177747		;CLOSE ALL CHANNELS
	CQTIMR=^O215
	BUFPAG==2
	BUF==256*BUFPAG
	STKEND==507
	CQSTAT=^O226
	CQHTIM=^O164104
	EXTIO==1
	TIME==1
	GETCMD==1
	CLMWID==10
	PI=255				;VALUE OF PI CHARACTER FOR COMMODORE.
	ROMSW==1
	RORSW==1
	TRMPOS=^O306>
IFE	REALIO-1,<GETCMD==1
	DISKO==1
	OUTCH=^O17240			;1EA0
	ROMLOC==^O20000
	RORSW==0
	CZGETL=^O17132>
IFE	REALIO-2,<
	RORSW==0
	RAMLOC==^O1000
IFN	ROMSW,<
	RORSW==0
	RAMLOC==^O100000>
	OUTCH==^O177013>
IFE	REALIO-4,<
	RORSW==1
	NULCMD==0
	GETCMD==1
	CQINLN==^O176547
	CQPRMP==^O63
	CQINCH==^O176414
	CQCOUT==^O177315
	CQCSIN==^O177375
	BUFPAG==2
	BUF=BUFPAG*256
	ROMLOC=^O4000
	RAMLOC=^O25000			;PAGE 2A
	OUTCH=^O176755
	CZGETL=^O176414
	LINLEN==40
	BUFLEN==240
	RORSW==1
	STKEND=507>
IFE	RORSW,<
DEFINE	ROR (WD),<
	LDAI	0
	BCC	.+4
	LDAI	^O200
	LSR	WD
	ORA	WD
	STA	WD>>

DEFINE ACRLF,<
	13
	10>
DEFINE	SYNCHK	(Q),<
	LDAI	<Q>
	JSR	SYNCHR>
DEFINE	DT(Q),<
IRPC	Q,<IFDIF <Q><">,<EXP "Q">>>
DEFINE	LDWD	(WD),<
	LDA	WD
	LDY	<WD>+1>
DEFINE	LDWDI	(WD),<
	LDAI	<<WD>&^O377>
	LDYI	<<WD>/^O400>>
DEFINE	LDWX	(WD),<
	LDA	WD
	LDX	<WD>+1>
DEFINE	LDWXI	(WD),<
	LDAI	<<WD>&^O377>
	LDXI	<<WD>/^O400>>
DEFINE	LDXY	(WD),<
	LDX	WD
	LDY	<WD>+1>
DEFINE	LDXYI	(WD),<
	LDXI	<<WD>&^O377>
	LDYI	<<WD>/^O400>>
DEFINE	STWD	(WD),<
	STA	WD
	STY	<WD>+1>
DEFINE	STWX	(WD),<
	STA	WD
	STX	<WD>+1>
DEFINE	STXY	(WD),<
	STX	WD
	STY	<WD>+1>
DEFINE	CLR	(WD),<
	LDAI	0
	STA	WD>
DEFINE	COM	(WD),<
	LDA	WD
	EORI	^O377
	STA	WD>
DEFINE	PULWD	(WD),<
	PLA
	STA	WD
	PLA
	STA	<WD>+1>
DEFINE	PSHWD	(WD),<
	LDA	<WD>+1
	PHA
	LDA	WD
	PHA>
DEFINE	JEQ	(WD),<
	BNE	.+5
	JMP	WD>
DEFINE	JNE	(WD),<
	BEQ	.+5
	JMP	WD>
DEFINE	BCCA(Q),<	BCC	Q>	;BRANCHES THAT ALWAYS BRANCH
DEFINE	BCSA(Q),<	BCS	Q>	;THESE ARE USED ON THE 6502 BECAUSE
DEFINE	BEQA(Q),<	BEQ	Q>	;THERE IS NO UNCONDITIONAL BRANCH
DEFINE	BNEA(Q),<	BNE	Q>
DEFINE	BMIA(Q),<	BMI	Q>
DEFINE	BPLA(Q),<	BPL	Q>
DEFINE	BVCA(Q),<	BVC	Q>
DEFINE	BVSA(Q),<	BVS	Q>
DEFINE	INCW(R),<
	INC	R
	BNE	%Q
	INC	R+1
%Q:>
DEFINE	SKIP1,	<XWD ^O1000,^O044>	;BIT ZERO PAGE TRICK.
DEFINE	SKIP2,	<XWD ^O1000,^O054>	;BIT ABS TRICK.
IF1,<
IFE	REALIO,<PRINTX/SIMULATE/>
IFE	REALIO-1,<PRINTX KIM>
IFE	REALIO-2,<PRINTX OSI>
IFE	REALIO-3,<PRINTX COMMODORE>
IFE	REALIO-4,<PRINTX APPLE>
IFE	REALIO-5,<PRINTX STM>
IFN	ADDPRC,<PRINTX ADDITIONAL PRECISION>
IFN	INTPRC,<PRINTX INTEGER ARRAYS>
IFN	LNGERR,<PRINTX LONG ERRORS>
IFN	DISKO,<PRINTX SAVE AND LOAD>
IFE	ROMSW,<PRINTX RAM>
IFN	ROMSW,<PRINTX ROM>
IFE	RORSW,<PRINTX NO ROR>
IFN	RORSW,<PRINTX ROR ASSUMED>>
PAGE
